FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/*.jar
copy ./target/offer-service-0.0.1-SNAPSHOT.jar offer-service-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","offer-service-0.0.1-SNAPSHOT.jar"]
RUN chmod 777 offer-service-0.0.1-SNAPSHOT.jarENTRYPOINT ["java", "-jar", "/app.jar"]
ENTRYPOINT ["java", "-jar", "/app.jar"]

offerservice/JenkinsFile

pipeline {
    agent  label {  'maven' } 
	options {timeout(time:40,unit:'MINUTES')}
	environment{
