FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/*.jar
copy ./target/language-service-0.0.1-SNAPSHOT.jar language-service-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","language-service-0.0.1-SNAPSHOT.jar"]
RUN chmod 777 language-service-0.0.1-SNAPSHOT.jarENTRYPOINT ["java", "-jar", "/app.jar"]
ENTRYPOINT ["java", "-jar", "/app.jar"]
