FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/*.jar
copy ./target/theatre-service-0.0.1-SNAPSHOT.jar theatre-service-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","theatre-service-0.0.1-SNAPSHOT.jar"]
RUN chmod 777 theatre-service-0.0.1-SNAPSHOT.jar ENTRYPOINT ["java", "-jar", "/app.jar"]
ENTRYPOINT ["java", "-jar", "/app.jar"]
