FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/*.jar
copy ./target/publish-service-0.0.1-SNAPSHOT.jar publish-service-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","publish-service-0.0.1-SNAPSHOT.jar"]
RUN chmod 777 publish-service-0.0.1-SNAPSHOT.jarENTRYPOINT ["java", "-jar", "/app.jar"]
ENTRYPOINT ["java", "-jar", "/app.jar"]
